# variables_generated.tf -- generated by: just extract-regions gcp
variable "atlas_to_gcp_region" {
  type = map(string)
  default = {
    AFRICA_SOUTH_1            = "africa-south1"
    ASIA_EAST_2               = "asia-east2"
    ASIA_NORTHEAST_2          = "asia-northeast2"
    ASIA_NORTHEAST_3          = "asia-northeast3"
    ASIA_SOUTHEAST_2          = "asia-southeast2"
    ASIA_SOUTH_1              = "asia-south1"
    ASIA_SOUTH_2              = "asia-south2"
    AUSTRALIA_SOUTHEAST_1     = "australia-southeast1"
    AUSTRALIA_SOUTHEAST_2     = "australia-southeast2"
    CENTRAL_US                = "us-central1"
    EASTERN_ASIA_PACIFIC      = "asia-east1"
    EASTERN_US                = "us-east1"
    EUROPE_CENTRAL_2          = "europe-central2"
    EUROPE_NORTH_1            = "europe-north1"
    EUROPE_SOUTHWEST_1        = "europe-southwest1"
    EUROPE_WEST_10            = "europe-west10"
    EUROPE_WEST_12            = "europe-west12"
    EUROPE_WEST_2             = "europe-west2"
    EUROPE_WEST_3             = "europe-west3"
    EUROPE_WEST_4             = "europe-west4"
    EUROPE_WEST_6             = "europe-west6"
    EUROPE_WEST_8             = "europe-west8"
    EUROPE_WEST_9             = "europe-west9"
    MIDDLE_EAST_CENTRAL_1     = "me-central1"
    MIDDLE_EAST_CENTRAL_2     = "me-central2"
    MIDDLE_EAST_WEST_1        = "me-west1"
    NORTHEASTERN_ASIA_PACIFIC = "asia-northeast1"
    NORTH_AMERICA_NORTHEAST_1 = "northamerica-northeast1"
    NORTH_AMERICA_NORTHEAST_2 = "northamerica-northeast2"
    NORTH_AMERICA_SOUTH_1     = "northamerica-south1"
    SOUTHEASTERN_ASIA_PACIFIC = "asia-southeast1"
    SOUTH_AMERICA_EAST_1      = "southamerica-east1"
    SOUTH_AMERICA_WEST_1      = "southamerica-west1"
    US_EAST_4                 = "us-east4"
    US_EAST_5                 = "us-east5"
    US_SOUTH_1                = "us-south1"
    US_WEST_2                 = "us-west2"
    US_WEST_3                 = "us-west3"
    US_WEST_4                 = "us-west4"
    WESTERN_EUROPE            = "europe-west1"
    WESTERN_US                = "us-west1"
  }
  description = <<-EOT
    Atlas to GCP region mapping. Keys = Atlas format, values = GCP format.
    The module accepts either format in all region inputs and normalizes internally.
    Override to restrict allowed regions or add custom mappings.
  EOT
}
