# Generated by workspace - do not edit manually
from pathlib import Path

import pytest

ACTUAL_DIR = Path(__file__).parent / "plan_snapshots_actual"
EXPECTED_DIR = Path(__file__).parent / "plan_snapshots"

# (example_id, sanitized_address, nested)
TEST_CASES = [
    ('encryption', 'google_kms_key_ring_atlas', True),
    ('encryption', 'google_kms_crypto_key_atlas', True),
    ('encryption', 'module_atlas_gcp_module_cloud_provider_access[0]_mongodbatlas_cloud_provider_access_setup_this', True),
    ('encryption', 'module_atlas_gcp_module_cloud_provider_access[0]_mongodbatlas_cloud_provider_access_authorization_this', True),
    ('encryption', 'module_atlas_gcp_module_encryption[0]_mongodbatlas_encryption_at_rest_this', True),
    ('encryption', 'module_atlas_gcp_module_encryption[0]_google_kms_crypto_key_iam_member_encrypter', True),
    ('encryption', 'module_atlas_gcp_module_encryption[0]_google_kms_crypto_key_iam_member_viewer', True),
]


@pytest.mark.parametrize("example_id,address,nested", TEST_CASES)
def test_plan_snapshot(
    example_id: str, address: str, nested: bool, file_regression
) -> None:
    subpath = f"{example_id}/{address}" if nested else f"{example_id}_{address}"
    actual_file = ACTUAL_DIR / f"{subpath}.yaml"
    expected_file = EXPECTED_DIR / f"{subpath}.yaml"
    assert actual_file.exists(), f'Actual file not found: {actual_file}'
    file_regression.check(actual_file.read_text(), fullpath=expected_file)
