# Generated by workspace - do not edit manually
from pathlib import Path

import pytest

ACTUAL_DIR = Path(__file__).parent / "plan_snapshots_actual"
EXPECTED_DIR = Path(__file__).parent / "plan_snapshots"

# (example_id, sanitized_address, nested)
TEST_CASES = [
    ('complete', 'module_atlas_gcp_module_cloud_provider_access[0]_mongodbatlas_cloud_provider_access_setup_this', True),
    ('complete', 'module_atlas_gcp_module_cloud_provider_access[0]_mongodbatlas_cloud_provider_access_authorization_this', True),
    ('complete', 'module_atlas_gcp_module_encryption[0]_google_kms_key_ring_atlas[0]', True),
    ('complete', 'module_atlas_gcp_module_encryption[0]_google_kms_crypto_key_atlas[0]', True),
    ('complete', 'module_atlas_gcp_module_encryption[0]_google_kms_crypto_key_iam_member_encrypter', True),
    ('complete', 'module_atlas_gcp_module_encryption[0]_google_kms_crypto_key_iam_member_viewer', True),
    ('complete', 'module_atlas_gcp_module_encryption[0]_mongodbatlas_encryption_at_rest_this', True),
    ('complete', 'module_atlas_gcp_module_backup_export[0]_google_storage_bucket_atlas[0]', True),
    ('complete', 'module_atlas_gcp_module_backup_export[0]_google_storage_bucket_iam_member_atlas', True),
    ('complete', 'module_atlas_gcp_module_backup_export[0]_mongodbatlas_cloud_backup_snapshot_export_bucket_this', True),
    ('complete', 'module_atlas_gcp_mongodbatlas_privatelink_endpoint_this["us-east4"]', True),
    ('complete', 'module_atlas_gcp_module_privatelink["us-east4"]_google_compute_address_atlas[0]', True),
    ('complete', 'module_atlas_gcp_module_privatelink["us-east4"]_google_compute_forwarding_rule_atlas[0]', True),
    ('complete', 'module_atlas_gcp_module_privatelink["us-east4"]_mongodbatlas_privatelink_endpoint_service_this', True),
    ('encryption', 'google_kms_key_ring_atlas', True),
    ('encryption', 'google_kms_crypto_key_atlas', True),
    ('encryption', 'module_atlas_gcp_module_cloud_provider_access[0]_mongodbatlas_cloud_provider_access_setup_this', True),
    ('encryption', 'module_atlas_gcp_module_cloud_provider_access[0]_mongodbatlas_cloud_provider_access_authorization_this', True),
    ('encryption', 'module_atlas_gcp_module_encryption[0]_mongodbatlas_encryption_at_rest_this', True),
    ('encryption', 'module_atlas_gcp_module_encryption[0]_google_kms_crypto_key_iam_member_encrypter', True),
    ('encryption', 'module_atlas_gcp_module_encryption[0]_google_kms_crypto_key_iam_member_viewer', True),
    ('backup_export', 'module_atlas_gcp_module_cloud_provider_access[0]_mongodbatlas_cloud_provider_access_setup_this', True),
    ('backup_export', 'module_atlas_gcp_module_cloud_provider_access[0]_mongodbatlas_cloud_provider_access_authorization_this', True),
    ('backup_export', 'module_atlas_gcp_module_backup_export[0]_google_storage_bucket_atlas[0]', True),
    ('backup_export', 'module_atlas_gcp_module_backup_export[0]_google_storage_bucket_iam_member_atlas', True),
    ('backup_export', 'module_atlas_gcp_module_backup_export[0]_mongodbatlas_cloud_backup_snapshot_export_bucket_this', True),
    ('privatelink_multi_region', 'module_atlas_gcp_mongodbatlas_private_endpoint_regional_mode_this[0]', True),
    ('privatelink_multi_region', 'module_atlas_gcp_mongodbatlas_privatelink_endpoint_this["us-east4"]', True),
    ('privatelink_multi_region', 'module_atlas_gcp_mongodbatlas_privatelink_endpoint_this["us-east1"]', True),
    ('privatelink_multi_region', 'module_atlas_gcp_module_privatelink["us-east4"]_google_compute_address_atlas[0]', True),
    ('privatelink_multi_region', 'module_atlas_gcp_module_privatelink["us-east4"]_google_compute_forwarding_rule_atlas[0]', True),
    ('privatelink_multi_region', 'module_atlas_gcp_module_privatelink["us-east4"]_mongodbatlas_privatelink_endpoint_service_this', True),
    ('privatelink_multi_region', 'module_atlas_gcp_module_privatelink["us-east1"]_google_compute_address_atlas[0]', True),
    ('privatelink_multi_region', 'module_atlas_gcp_module_privatelink["us-east1"]_google_compute_forwarding_rule_atlas[0]', True),
    ('privatelink_multi_region', 'module_atlas_gcp_module_privatelink["us-east1"]_mongodbatlas_privatelink_endpoint_service_this', True),
    ('privatelink_byoe', 'module_atlas_gcp_mongodbatlas_privatelink_endpoint_this["ep1"]', True),
    ('privatelink_byoe', 'module_atlas_gcp_module_privatelink["ep1"]_mongodbatlas_privatelink_endpoint_service_this', True),
    ('privatelink_byoe', 'google_compute_address_psc', True),
    ('privatelink_byoe', 'google_compute_forwarding_rule_psc', True),
]


@pytest.mark.parametrize("example_id,address,nested", TEST_CASES)
def test_plan_snapshot(
    example_id: str, address: str, nested: bool, file_regression
) -> None:
    subpath = f"{example_id}/{address}" if nested else f"{example_id}_{address}"
    actual_file = ACTUAL_DIR / f"{subpath}.yaml"
    expected_file = EXPECTED_DIR / f"{subpath}.yaml"
    assert actual_file.exists(), f'Actual file not found: {actual_file}'
    file_regression.check(actual_file.read_text(), fullpath=expected_file)
